// REGISTER
export const SET_REGISTER_STATE = "SET_REGISTER_STATE";
export const SET_REGISTER_SUCCESS = "SET_REGISTER_SUCCESS";
export const SET_REGISTER_FAILD = "SET_REGISTER_FAILD";

// LOGIN
export const SET_INITIAL_STATE = "SET_INITIAL_STATE";
export const SET_LOGIN_STATE = "SET_LOGIN_STATE";
export const SET_LOGIN_FAIL_STATE = "SET_LOGIN_FAIL_STATE"; 
export const SET_LOGIN_SUCCESS = "SET_LOGIN_SUCCESS";

// LOGOUT
export const SET_LOGOUT_STATE = "SET_LOGOUT_STATE"; 

// USER
export const SET_USER_STATE = "SET_USER_STATE"; 
export const SET_USER_SUCCESS = "SET_USER_SUCCESS"; 
export const SET_USER_FAILD = "SET_USER_FAILD"; 

//ROOM
export const SET_ROOM_STATE = "SET_ROOM_STATE"; 
export const SET_ROOM_SUCCESS = "SET_ROOM_SUCCESS"; 
export const SET_ROOM_FAILD = "SET_ROOM_FAILD"; 

//ROOMS
export const SET_ROOMS_STATE = "SET_ROOMS_STATE"; 
export const SET_ROOMS_SUCCESS = "SET_ROOMS_SUCCESS"; 
export const SET_ROOMS_FAILD = "SET_ROOMS_FAILD";

//TYPE ROOM
export const SET_TYPEROOM_STATE = "SET_TYPEROOM_STATE"; 
export const SET_TYPEROOM_SUCCESS = "SET_TYPEROOM_SUCCESS"; 
export const SET_TYPEROOM_FAILD = "SET_TYPEROOM_FAILD"; 